---
AWSTemplateFormatVersion: "2010-09-09"
Description: Delete stac

Resources:

  DeleteRol:
    Type: AWS::IAM::Role
    Properties:
      RoleName:  sct-vista360-back-rolDeploy-dev
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: sct-vista360-back-rolDeploy-dev
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"
